### ISSUE TITLE
"Kubernetes Master branch and Driver" failing for a long time

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#649]
`Kubernetes Master branch and Driver` aka `ci-gcp-compute-persistent-disk-csi-driver-latest-k8s-master-integration` appears to have been failing as far back as we have history (Oct 15) in the test grid: https://testgrid.k8s.io/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Latest

Overall test failure prevents any tests from running.

The error appears to be:

```
W1030 13:31:06.060] F1030 13:31:06.060280    3088 main.go:161] Failed to run integration test: failed to install CSI Driver: failed to install kustomize: installing kustomize
W1030 13:31:06.061] curl: no URL specified!
W1030 13:31:06.061] curl: try 'curl --help' or 'curl --manual' for more information
W1030 13:31:06.061] , err: exit status 123
W1030 13:31:06.065] Traceback (most recent call last):
W1030 13:31:06.065]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W1030 13:31:06.066]     main(ARGS.env, ARGS.cmd + ARGS.args)
W1030 13:31:06.066]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W1030 13:31:06.066]     check(*cmd)
W1030 13:31:06.066]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W1030 13:31:06.066]     subprocess.check_call(cmd)
W1030 13:31:06.066]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W1030 13:31:06.067]     raise CalledProcessError(retcode, cmd)
W1030 13:31:06.067] subprocess.CalledProcessError: Command '('test/run-k8s-integration-ci.sh',)' returned non-zero exit status 255
E1030 13:31:06.073] Command failed
I1030 13:31:06.073] process 448 exited with code 1 after 30.4m
E1030 13:31:06.073] FAIL: ci-gcp-compute-persistent-disk-csi-driver-latest-k8s-master-integration
```

**Comment by saad-ali** [comment]
This is blocking 1.1 release

**Comment by saad-ali** [comment]
Per Jing this should be fixed by https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/647

**Comment by saad-ali** [comment]
Let's leave this open until test grid turns back to green.

**Comment by saad-ali** [comment]
@jingxu97 Tests are still failing, even though #647 is merged with the same error: `failed to install CSI Driver`.

```
W1102 06:03:00.654] F1102 06:03:00.654296    3069 main.go:161] Failed to run integration test: failed to install CSI Driver: driver failed to come up: exit status 255
W1102 06:03:00.663] Traceback (most recent call last):
W1102 06:03:00.664]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W1102 06:03:00.664]     main(ARGS.env, ARGS.cmd + ARGS.args)
W1102 06:03:00.664]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W1102 06:03:00.664]     check(*cmd)
W1102 06:03:00.664]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W1102 06:03:00.665]     subprocess.check_call(cmd)
W1102 06:03:00.665]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W1102 06:03:00.665]     raise CalledProcessError(retcode, cmd)
W1102 06:03:00.665] subprocess.CalledProcessError: Command '('test/run-k8s-integration-ci.sh',)' returned non-zero exit status 255
E1102 06:03:00.686] Command failed
I1102 06:03:00.687] process 438 exited with code 1 after 47.1m
E1102 06:03:00.688] FAIL: ci-gcp-compute-persistent-disk-csi-driver-latest-k8s-master-integration
```

**Comment by jingxu97** [comment]
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/654 fixed it.
