### ISSUE TITLE
`Kubernetes Master Driver Release 0.7` tests failing for a long time

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#651]
`Kubernetes Master Driver Release 0.7` aka `ci-gcp-compute-persistent-disk-csi-driver-release-0-7-k8s-master-integration` has been failing for as long as we have history in test grid (Oct 15): https://testgrid.k8s.io/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Release%200.7

Error:

```
I1030 20:38:57.858] Call:  /workspace/./test-infra/jenkins/../scenarios/execute.py test/run-k8s-integration-ci.sh
W1030 20:38:57.884] Run: ('test/run-k8s-integration-ci.sh',)
W1030 20:38:57.893] Traceback (most recent call last):
W1030 20:38:57.894]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W1030 20:38:57.894]     main(ARGS.env, ARGS.cmd + ARGS.args)
W1030 20:38:57.894]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W1030 20:38:57.894]     check(*cmd)
W1030 20:38:57.894]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W1030 20:38:57.894]     subprocess.check_call(cmd)
W1030 20:38:57.895]   File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
W1030 20:38:57.895]     retcode = call(*popenargs, **kwargs)
W1030 20:38:57.895]   File "/usr/lib/python2.7/subprocess.py", line 172, in call
W1030 20:38:57.895]     return Popen(*popenargs, **kwargs).wait()
W1030 20:38:57.895]   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
W1030 20:38:57.895]     errread, errwrite)
W1030 20:38:57.895]   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
W1030 20:38:57.896]     raise child_exception
W1030 20:38:57.896] OSError: [Errno 2] No such file or directory
E1030 20:38:57.899] Command failed
I1030 20:38:57.899] process 437 exited with code 1 after 0.0m
```

**Comment by saad-ali** [comment]
Fixed by #655
Test grid is green mod some test failures.
